### ISSUE TITLE
Returned data formatting

### ISSUE THREAD

**Issue by cwjoshuak** [FoothillCSClub/OwlAPI#35]
For `https://floof.li/fh/single?dept=POLI`
Data returned where there are spaces before the number in units:
```json
[
  {
    "1" : {
      "42082" : [
        {
          "room" : "ONLINE",
          "units" : "  5.00",
          "end" : "06\/29\/2018",
          "start" : "05\/21\/2018",
          "campus" : "FH",
          "desc" : "POLI SCI:INTRO AMERICAN GOVN\/P",
          "CRN" : "42082",
          "course" : "POLI F001.14W",
          "status" : "Waitlist",
          "wait_cap" : "20",
          "instructor" : "Callow",
          "days" : "TBA",
          "time" : "TBA",
          "seats" : "0",
          "wait_seats" : "15"
        }
      ]
    }
  }
]
```
It's also prevalent in other calls `https://floof.li/da/single?dept=JOUR`
Not that it really matters but letting you know.

Also, something new I discovered if you didn't know already
`https://floof.li/da/single?dept=NURS`
![image](https://user-images.githubusercontent.com/15935660/39964726-19716418-5640-11e8-8707-8f5dc540e5d9.png)
There apparently are possible locations out of campus- `DO` refers to `DO HOSP` in myPortal under Location.. and it crashes my application because I hardcoded locations. wuu. ;_;

**Comment by phi-line** [comment]
If that would help you, I could remove the spaces before the number of units. I did not do that up to this point because the data is pulled as is directly from MyPortal without modification.

As for the location, there is a similar case found for Foothill with the Foothill Sunnyvale campus. Let me know if there are any more issues with data like with the units. I'd be happy to fix those to make your life easier.

**Comment by phi-line** [comment]
This issue has been resolved with PR #39.
Spaces have been removed from the units key

**Comment by cwjoshuak** [comment]
@phi-line It was okay actually, I thought it was an overlook on how you parsed the data.

So far I've encountered campuses with letters 
```
FH
DA
FC
DO
FO
```

**Comment by phi-line** [comment]
Okay thank you for bringing the locations to my attention
