### ISSUE TITLE
Add a style guide for contributors

### ISSUE THREAD

**Issue by TryExceptElse** [FoothillCSClub/OwlAPI#52]
A style guide would be a helpful aid for people contributing to the project, in order to help maintain a consistent style, and therefore readability, throughout the project.

**Comment by phi-line** [comment]
Yeah I can look into making a git hook that enforces some style guide like PEP-8. We can alternatively get something that would work with the continuous integration.

**Comment by TryExceptElse** [comment]
A simple documentation file could be enough, but if you want automation, theres tools like [pylint](https://www.pylint.org/) which could be used with a premade rc file such as [this one based on google's style guide](https://gist.github.com/rpunkfu/3cd6f8b8b23e27adedbd)
